services:
  spring_app:
    container_name: spring_scaffolding_grupob
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_custom
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_custom:3306/sisacad
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - spring_net

  mysql_custom:
    container_name: mysql_custom
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sisacad
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sisacad.sql:/docker-entrypoint-initdb.d/sisacad.sql
    networks:
      - spring_net

networks:
  spring_net:

volumes:
  mysql_data:
